name=input("name        :")
erp=input("erp no       :")
coll=input("college name:")
sec=input("section      :")
mob=input("mobile no    :")
age=input("age          :")
print(name)
print(erp)
print(coll)
print(sec)
print(mob)
print(age)